apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
spec:
  replicas: 2
  selector:
    matchLabels:
        app: web1
  template:
    metadata:
       labels:
          app: web1
    spec:
        containers:
        - name: cont1
          image: asifkoenigmeerut/new-image:v1.2

